'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {AnimatePresence,motion,useInView,useReducedMotion,animate} from 'framer-motion';
import {Swiper,SwiperSlide} from 'swiper/react';
import {Navigation,Pagination,A11y} from 'swiper/modules';
import 'swiper/css'; import 'swiper/css/navigation'; import 'swiper/css/pagination';
import {ChevronLeft,ChevronRight,Pause,Play,MapPin,Plane,BookOpen,Compass,Heart,ShieldCheck,Hotel,Check,Star,Plus,Minus,Clock} from 'lucide-react';
import {trips,services,visas,faqs,reviews,type Trip} from '@/data/travel';
import {ButtonLink,Heading,Picture,Reveal} from './ui';
const icons={plane:Plane,passport:BookOpen,map:Compass,heart:Heart,shield:ShieldCheck,hotel:Hotel};
const slides=[{trip:trips[0],title:<>A little further.<br/>A little <em>freer.</em></>,text:'Trade the everyday for somewhere extraordinary. Thoughtfully planned journeys, made personal.',location:'UBUD, BALI · INDONESIA'}, {trip:trips[1],title:<>Follow your<br/>sense of <em>wonder.</em></>,text:'Winding streets. Open skies. A journey filled with the moments you’ll keep coming back to.',location:'CAPPADOCIA · TÜRKİYE'}, {trip:trips[2],title:<>Find a place<br/>to just <em>be.</em></>,text:'Slow mountain mornings and a new perspective. Your next adventure could be closer than you think.',location:'HUNZA VALLEY · PAKISTAN'}, {trip:trips[3],title:<>Into the<br/><em>wild.</em></>,text:'Crystal clear lakes and towering peaks. Experience nature at its most majestic.',location:'BANFF · CANADA'}, {trip:trips[4],title:<>Echoes of an<br/><em>empire.</em></>,text:'Grand architecture and timeless artistry. Discover the soul of imperial Russia.',location:'MOSCOW · RUSSIA'}];
export function Hero(){const [index,setIndex]=useState(0);const [paused,setPaused]=useState(false);const reduced=useReducedMotion();const touch=useRef(0);useEffect(()=>{if(paused||reduced)return;const id=setInterval(()=>setIndex(i=>(i+1)%slides.length),7000);return()=>clearInterval(id)},[paused,reduced]);const slide=slides[index];return <section className="hero" aria-roledescription="carousel" aria-label="Featured journeys" onTouchStart={e=>touch.current=e.touches[0].clientX} onTouchEnd={e=>{const d=e.changedTouches[0].clientX-touch.current;if(Math.abs(d)>50)setIndex(i=>(i+(d<0?1:slides.length-1))%slides.length)}}><div className="hero-images">{slides.map((s,i)=><motion.div key={s.trip.slug} className="hero-image" animate={{opacity:i===index?1:0,scale:reduced?1:i===index?1.035:1}} transition={{opacity:{duration:.9},scale:{duration:7,ease:'linear'}}}><Picture src={s.trip.image} alt={s.location} priority={i===0}/></motion.div>)}</div><div className="hero-shade"/><div className="container hero-content"><span className="hero-eyebrow"><span/> NOT JUST A TRIP. YOUR KIND OF JOURNEY.</span><AnimatePresence mode="wait"><motion.div key={index} initial={reduced?false:{opacity:0,y:15}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-10}} transition={{duration:.35}}><h1>{slide.title}</h1><p>{slide.text}</p></motion.div></AnimatePresence><div className="hero-buttons"><ButtonLink href="/packages">Find my next adventure</ButtonLink><ButtonLink href="/contact" secondary>Let’s plan together</ButtonLink></div><div className="hero-proof"><ShieldCheck size={18}/><span>Personal planning</span><span className="proof-divider"/><span>Transparent guidance</span></div></div><div className="container hero-bottom"><span className="hero-location"><MapPin size={16}/>{slide.location}</span><div className="slider-controls"><span className="slide-number">0{index+1} <small>/ 0{slides.length}</small></span><button aria-label="Previous hero slide" onClick={()=>setIndex((index+slides.length-1)%slides.length)}><ChevronLeft/></button>{slides.map((s,i)=><button key={s.trip.slug} className={`slide-dot ${i===index?'active':''}`} aria-label={`Show slide ${i+1}`} aria-pressed={i===index} onClick={()=>setIndex(i)}/>)}<button aria-label="Next hero slide" onClick={()=>setIndex((index+1)%slides.length)}><ChevronRight/></button><button aria-label={paused?'Play slideshow':'Pause slideshow'} onClick={()=>setPaused(!paused)}>{paused?<Play size={16}/>:<Pause size={16}/>}</button></div></div></section>}
export function Marquee(){return <div className="marquee" aria-label="Destinations: Bali, Türkiye, Hunza, Malaysia, Dubai, Saudi Arabia, Canada, Russia"><div className="marquee-track">{[0,1].map(i=><div key={i} aria-hidden="true">{['BALI','TÜRKİYE','HUNZA','CANADA','RUSSIA','MALAYSIA','DUBAI','SAUDI ARABIA'].map(n=><span key={n}><Compass size={17}/>{n}</span>)}</div>)}</div></div>}
export function TripCard({trip,packageMode=false}:{trip:Trip;packageMode?:boolean}){return <article className="trip-card"><Link href={`/packages/${trip.slug}`} className="trip-image"><Picture src={trip.image} alt={`${trip.country} landscape`}/><span className="trip-tag">{trip.tag}</span><span className="trip-country"><MapPin size={14}/>{trip.country}</span></Link><div className="trip-body"><div className="trip-meta"><span><Clock size={15}/>{trip.days} days</span><span>Made for discovery</span></div><h3><Link href={`/packages/${trip.slug}`}>{trip.name}</Link></h3>{packageMode&&<p>{trip.summary}</p>}<div className="trip-bottom"><div><small>Sample estimate from</small><strong>PKR {trip.price.toLocaleString('en-US')}</strong><small>per person · twin sharing</small></div><Link className="text-link" href={`/packages/${trip.slug}`}>Explore trip</Link></div></div></article>}
export function Destinations(){return <section className="section container"><Reveal className="heading-row"><Heading eyebrow="SOMEWHERE THAT MOVES YOU" title="Where will your curiosity take you?" text="A few of our favourite starting points. Every journey can be made your own."/><Link href="/tours" className="text-link">Explore destinations</Link></Reveal><div className="trip-grid">{trips.map(t=><Reveal key={t.slug}><TripCard trip={t}/></Reveal>)}</div></section>}
export function Services(){return <section className="section service-section"><div className="container"><Reveal className="heading-row"><Heading eyebrow="THE DETAILS, TAKEN CARE OF" title="You dream it. We help you get there."/><Link href="/services" className="text-link">All travel services</Link></Reveal><div className="service-grid">{services.map(s=>{const Icon=icons[s.icon as keyof typeof icons];return <Reveal key={s.slug}><Link className="service-card" href={`/${s.slug}`}><Icon size={29}/><h3>{s.name}</h3><p>{s.text}</p><span className="text-link">Let’s explore</span></Link></Reveal>})}</div></div></section>}
export function VisaCards(){return <div className="visa-grid">{visas.map(v=><Link className="visa-card" href={`/contact?service=Visa+assistance&destination=${encodeURIComponent(v.country)}`} key={v.code}><span className="country-code">{v.code}</span><div><h3>{v.country}</h3><p>{v.type}</p><span className="text-link">Ask about requirements</span></div><BookOpen size={22}/></Link>)}</div>}
function Counter({value}:{value:number}){const ref=useRef<HTMLSpanElement>(null);const inView=useInView(ref,{once:true});const reduced=useReducedMotion();useEffect(()=>{if(!inView||!ref.current)return;const ctrl=animate(0,value,{duration:reduced?0:1.5,onUpdate:n=>{if(ref.current)ref.current.textContent=Math.round(n).toString()}});return()=>ctrl.stop()},[inView,value,reduced]);return <span ref={ref}>0</span>}
export function Why(){return <section className="section container why"><Reveal className="why-image"><Picture src={trips[2].image} alt="Attabad Lake beneath the Hunza mountains"/><div className="image-caption">Less rush.<br/><em>More remarkable.</em></div></Reveal><Reveal><Heading eyebrow="A DIFFERENT WAY TO TRAVEL" title="Big on the world. Thoughtful about you." text="The best trips aren’t measured in miles. They’re measured in the moments that stay with you."/><div className="why-list">{[['A real person, from day one','A dedicated point of contact to listen, guide and help you plan.'],['Your pace. Your priorities.','Room for the things you love, without a one-size-fits-all itinerary.'],['Clear from the beginning','Understand inclusions, estimates and booking terms before committing.']].map(([title,text])=><div key={title}><span><Check size={19}/></span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div><div className="stats"><div><strong><Counter value={3}/></strong><span>Sample journeys</span></div><div><strong><Counter value={6}/></strong><span>Travel services</span></div><div><strong>1:1</strong><span>Personal planning</span></div></div></Reveal></section>}
export function Testimonials(){return <section className="section testimonial-section"><div className="container"><Heading eyebrow="MOMENTS WORTH SHARING" title="Good journeys make great stories." text="Illustrative stories from fictional travellers — replace with your own verified reviews."/><Swiper modules={[Navigation,Pagination,A11y]} navigation pagination={{clickable:true}} spaceBetween={25} slidesPerView={1} breakpoints={{850:{slidesPerView:2},1200:{slidesPerView:3}}}>{reviews.map(r=><SwiperSlide key={r.name}><article className="review"><div className="stars" aria-label="5 out of 5 stars">{[1,2,3,4,5].map(i=><Star key={i} size={16} fill="currentColor"/>)}</div><blockquote>“{r.quote}”</blockquote><div className="review-person"><span>{r.name[0]}</span><div><strong>{r.name}</strong><small>{r.place} · Sample story</small></div></div></article></SwiperSlide>)}</Swiper></div></section>}
export function FAQ(){const [open,setOpen]=useState<number|null>(0);return <section className="section container faq-section"><Heading eyebrow="BEFORE YOU GO" title="A few things you might be wondering." text="Have another question? We’re happy to help."/><div className="faqs">{faqs.map((f,i)=><div className="faq" key={f.q}><h3><button aria-expanded={open===i} aria-controls={`faq-${i}`} id={`question-${i}`} onClick={()=>setOpen(open===i?null:i)}>{f.q}{open===i?<Minus size={19}/>:<Plus size={19}/>}</button></h3><div id={`faq-${i}`} role="region" aria-labelledby={`question-${i}`} hidden={open!==i}><p>{f.a}</p></div></div>)}</div></section>}
export function TrendingDeals(){return <section className="section container trending-deals"><Reveal className="heading-row"><Heading eyebrow="LIMITED TIME OFFERS" title="Trending Deals" text="Special packages curated for this season at unbeatable prices."/><Link href="/packages" className="text-link">View all deals</Link></Reveal><div className="trip-grid"><Reveal><TripCard trip={{...trips[3], price: 345000, tag: "HOT DEAL"}}/></Reveal><Reveal><TripCard trip={{...trips[1], price: 215000, tag: "20% OFF"}}/></Reveal><Reveal><TripCard trip={{...trips[4], price: 245000, tag: "FLASH SALE"}}/></Reveal></div></section>}
export function CTA(){return <section className="container cta cta-bg"><div><span className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</span><h2>Somewhere wonderful<br/>is waiting.</h2><p>Tell us what you’re imagining. We’ll help with the rest.</p></div><ButtonLink href="/contact">Let’s plan your journey</ButtonLink></section>}
export function Home(){return <><Hero/><Marquee/><Destinations/><TrendingDeals/><Services/><Why/><section className="section visa-section"><div className="container"><div className="heading-row"><Heading eyebrow="A CLEARER PATH TO DEPARTURE" title="Visa paperwork, made less overwhelming." text="Document guidance and application support. Decisions remain with the relevant authorities."/><Link href="/visa" className="text-link">Explore visa assistance</Link></div><VisaCards/></div></section><section className="container tracker-banner"><div><BookOpen size={34}/><span><h2>Already started your journey?</h2><p>Explore our demo application timeline.</p></span></div><ButtonLink href="/track" secondary>Track an application</ButtonLink></section><section className="section container"><Heading eyebrow="YOUR TIME, WELL SPENT" title="Thoughtful itineraries. Extraordinary days."/><div className="trip-grid">{trips.map(t=><TripCard key={t.slug} trip={t} packageMode/>)}</div><p className="disclaimer">Sample estimates only. Request a personalised quote for dates, inclusions and current pricing.</p></section><Testimonials/><FAQ/><CTA/></>}
