'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {AnimatePresence,motion,useReducedMotion} from 'framer-motion';
import {Compass,Menu,X,MessageCircle,ChevronUp,Plane,LoaderCircle} from 'lucide-react';
import {useEffect,useRef,useState} from 'react';
import {site} from '@/config/site';
import {nav,services} from '@/data/travel';
export function Shell({children}:{children:React.ReactNode}){
 const path=usePathname(); const [menu,setMenu]=useState(false); const [scrolled,setScrolled]=useState(false); const [chat,setChat]=useState(false); const reduce=useReducedMotion(); const close=useRef<HTMLButtonElement>(null); const trigger=useRef<HTMLButtonElement>(null);
 useEffect(()=>{const run=()=>setScrolled(window.scrollY>30);run();window.addEventListener('scroll',run,{passive:true});return()=>window.removeEventListener('scroll',run)},[]);
 useEffect(()=>{if(!menu)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';close.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setMenu(false);trigger.current?.focus()}if(e.key==='Tab'){const buttons=document.querySelectorAll<HTMLElement>('.mobile-menu button,.mobile-menu a');const first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};window.addEventListener('keydown',key);return()=>{document.body.style.overflow=old;window.removeEventListener('keydown',key)}},[menu]);
 return <><a className="skip" href="#main">Skip to content</a><header className={`nav ${scrolled?'scrolled':''}`}><div className="container nav-inner"><Link href="/" className="brand" aria-label="Roamora home"><Compass size={30}/>{site.name}<span>TRAVEL, THOUGHTFULLY.</span></Link><nav className="desktop-nav" aria-label="Main navigation">{nav.map(n=><Link key={n.href} href={n.href} aria-current={path===n.href?'page':undefined}>{n.label}</Link>)}</nav><div className="nav-actions"><Link className="track-link" href="/track">Track application</Link><Link className="button small" href="/contact">Plan my trip</Link><button className="menu-toggle icon-button" ref={trigger} onClick={()=>setMenu(true)} aria-label="Open menu" aria-expanded={menu}><Menu/></button></div></div></header>
 <AnimatePresence>{menu&&<motion.div className="mobile-menu" role="dialog" aria-modal="true" aria-label="Navigation" initial={{opacity:0,x:'100%'}} animate={{opacity:1,x:0}} exit={{opacity:0,x:'100%'}} transition={{type:'spring',damping:25,stiffness:200}}><div className="mobile-top"><span className="brand">Roamora</span><button ref={close} className="icon-button" aria-label="Close menu" onClick={()=>{setMenu(false);trigger.current?.focus()}}><X/></button></div>{[...nav,{label:'All services',href:'/services'},{label:'Track application',href:'/track'},{label:'Contact us',href:'/contact'}].map(n=><Link key={n.href} href={n.href} onClick={()=>setMenu(false)}>{n.label}</Link>)}<p>Less planning. More possibility.</p></motion.div>}</AnimatePresence>
 <motion.main id="main" key={path} initial={reduce?false:{opacity:0}} animate={{opacity:1}} transition={{duration:.25}}>{children}</motion.main><Newsletter/>
 <footer><div className="container footer-grid"><div><Link href="/" className="brand"><Compass/>{site.name}</Link><p>For the places you’ve dreamed of.<br/>And the ones you haven’t found yet.</p><span className="footer-caption">ORIGINAL JOURNEYS. PERSONAL ATTENTION.</span></div><div><h3>Explore</h3>{[{label:'Our story',href:'/about'},...nav.slice(0,3),{label:'All services',href:'/services'}].map(n=><Link key={n.href} href={n.href}>{n.label}</Link>)}</div><div><h3>Travel services</h3>{services.filter(s=>s.slug!=='contact').map(s=><Link key={s.slug} href={`/${s.slug}`}>{s.name}</Link>)}</div><div><h3>Let’s talk travel</h3><Link href="/contact">Contact & consultation</Link><Link href="/track">Demo application tracker</Link><p>{site.email}<br/>{site.phone}<br/>{site.address}</p><small>{site.hours}</small></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} {site.name}. All journeys begin somewhere.</span><Link href="/contact#information">Business details & privacy</Link></div></footer>
 <div className="floating">{scrolled&&<button className="float top" onClick={()=>window.scrollTo({top:0,behavior:reduce?'instant':'smooth'})} aria-label="Back to top"><ChevronUp/></button>}<button className="float whatsapp" onClick={()=>site.whatsapp?window.open(`https://wa.me/${site.whatsapp.replace(/\D/g,'')}`,'_blank','noopener,noreferrer'):setChat(!chat)} aria-label="WhatsApp contact"><MessageCircle/></button></div>{chat&&<div className="chat-note"><button aria-label="Close contact notice" onClick={()=>setChat(false)}><X size={18}/></button><strong>Let’s plan something good.</strong><p>WhatsApp will be available when the business number is configured.</p><Link href="/contact" onClick={()=>setChat(false)}>Use the enquiry form</Link></div>}</>;
}
function Newsletter(){const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');return <section className="newsletter"><div className="container newsletter-inner"><div><span className="eyebrow">A LITTLE INSPIRATION</span><h2>Your next journey, in your inbox.</h2><p>Fresh ideas for places worth going.</p></div><form onSubmit={async e=>{e.preventDefault();setBusy(true);await new Promise(r=>setTimeout(r,600));setMessage('Demo complete — your email has not been subscribed.');setBusy(false)}}><label className="sr-only" htmlFor="newsletter">Email address</label><div className="newsletter-input"><input id="newsletter" type="email" required placeholder="Your email address"/><button disabled={busy} aria-label="Subscribe to newsletter">{busy?<LoaderCircle className="spin"/>:<Plane size={20}/>}</button></div><small>No spam. Just possibility. Demo signup.</small><p role="status">{message}</p></form></div></section>}
